server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/distributeddb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
